---
version: "3.8"
services:
  swag:
    image: ghcr.io/ephphatha/swag:main
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - EMAIL=ephphatha@thelettereph.com
      - URL=dbqp.dev
      - SUBDOMAINS=wildcard
      - ONLY_SUBDOMAINS=false
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - CLOUDFLARE_API_TOKEN_FILE=/run/secrets/cloudflare.token
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    secrets:
      - source: cloudflare-dbqp-dns
        target: cloudflare.token
        mode: 0400
    volumes:
      - swag_certs:/config/keys/

secrets:
  cloudflare-dbqp-dns:
    external: true

volumes:
  swag_certs: