---
version: "3.8"
services:
  swag:
    build:
      context: .
      dockerfile: swag.Dockerfile
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - DNSPLUGIN=cloudflare
      - URL=dbqp.dev
      - SUBDOMAINS=wildcard
      - ONLY_SUBDOMAINS=false
      - VALIDATION=dns
      - EMAIL=ephphatha@thelettereph.com
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    secrets:
      - source: cloudflare-dbqp-dns
        target: cloudflare.token
        mode: 0400

secrets:
  cloudflare-dbqp-dns:
    external: true